/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dm.view;

import dm.po.User;
import dm.util.FrameUtil;
import dm.util.LocationUtil;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LIUYIYU
 */
public class StudentFrame extends javax.swing.JFrame {
    
    public static User u;
    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();
        this.setTitle("用户—学生");
        LocationUtil.setFullScreen(this);
        LocationUtil.setScreenCenter(this); //窗口居中

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        myinfo = new javax.swing.JButton();
        mydorm = new javax.swing.JButton();
        mymail = new javax.swing.JButton();
        fixapply = new javax.swing.JButton();
        curfew = new javax.swing.JButton();
        leave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logout.setText("注销");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        myinfo.setText("个人中心");
        myinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myinfoActionPerformed(evt);
            }
        });

        mydorm.setText("我的宿舍");
        mydorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mydormActionPerformed(evt);
            }
        });

        mymail.setText("我的快递");
        mymail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mymailActionPerformed(evt);
            }
        });

        fixapply.setText("报修申请");
        fixapply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixapplyActionPerformed(evt);
            }
        });

        curfew.setText("晚归申请");
        curfew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curfewActionPerformed(evt);
            }
        });

        leave.setText("离校信息");
        leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mydorm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mymail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fixapply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(curfew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mydorm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mymail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fixapply, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(curfew, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(leave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveActionPerformed
        SleaveFrame.u = this.u;
        showFrame(SleaveFrame.class);
    }//GEN-LAST:event_leaveActionPerformed

    private void myinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myinfoActionPerformed
        SmyInfoFrame.u = this.u;
        showFrame(SmyInfoFrame.class);
    }//GEN-LAST:event_myinfoActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // 注销
        JOptionPane.showMessageDialog(this, "注销成功！");
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.dispose();
      
    }//GEN-LAST:event_logoutActionPerformed

    private void mydormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mydormActionPerformed
        SmyDormFrame.u = this.u;
        showFrame(SmyDormFrame.class);
    }//GEN-LAST:event_mydormActionPerformed

    private void mymailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mymailActionPerformed
        SmyMailFrame.u = this.u;
        showFrame(SmyMailFrame.class);
    }//GEN-LAST:event_mymailActionPerformed

    private void curfewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curfewActionPerformed
        ScurFrame.u = this.u;

        showFrame(ScurFrame.class);
    }//GEN-LAST:event_curfewActionPerformed

    private void fixapplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixapplyActionPerformed
        SfixFrame.u = this.u;
        showFrame(SfixFrame.class);
    }//GEN-LAST:event_fixapplyActionPerformed

    //显示窗体内容
    public void showFrame(Class clazz) {
        try {
            // new 对象
            JInternalFrame frame = FrameUtil.buildFrame(clazz);
            this.remove(frame);
            // 桌面容器再添加
            this.add(frame);
            // 显示
            LocationUtil.setScreenCenter(frame);
            frame.setVisible(true);
            // 显示在最前
            frame.toFront();
            // 处于选中状态
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            
            Logger.getLogger(StudentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton curfew;
    private javax.swing.JButton fixapply;
    private javax.swing.JButton leave;
    private javax.swing.JButton logout;
    private javax.swing.JButton mydorm;
    private javax.swing.JButton myinfo;
    private javax.swing.JButton mymail;
    // End of variables declaration//GEN-END:variables
}
