/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dm.view;
import dm.biz.tManageStuBiz;
import dm.biz.tManageStuBizImpl;
import dm.vo.tManageStu;
import dm.util.StringUtil;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 晨晨
 */
public class TmanageStuFrame extends javax.swing.JInternalFrame {
    tManageStuBiz sbiz = new tManageStuBizImpl();
    /**
     * Creates new form TmanageStuFrame
     */
    String shortname;
    public TmanageStuFrame() {
        initComponents();
        this.btnDelete.setEnabled(false);
        this.btnSave.setEnabled(false);
        //this.yearBox.setEnabled(false);
        //this.startMBox.setEnabled(false);
        //this.endMBox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabStudent = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        cobCondition = new javax.swing.JComboBox();
        txtCondition = new javax.swing.JTextField();
        btnLoad = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSsex = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSgrade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSdept = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        yearBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        startMBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        endMBox = new javax.swing.JComboBox();
        start = new com.ouc.cpss.util.DateChooserJButton();
        end = new com.ouc.cpss.util.DateChooserJButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tabStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "学号", "姓名", "性别", "年级", "院系", "宿舍号", "入住时间"
            }
        ));
        tabStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabStudent);

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cobCondition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "按学号", "按姓名", "按性别", "按年级", "按院系", "按宿舍号", "按入住时间", "模糊查询", " " }));

        btnLoad.setText("载入");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnAdd.setText("新增");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("修改/保存");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("重置");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnQuit.setText("退出");

        jLabel1.setText("学号：");

        jLabel2.setText("姓名：");

        jLabel3.setText("性别：");

        jLabel4.setText("年级：");

        jLabel5.setText("院系：");

        jLabel6.setText("宿舍号：");

        jLabel7.setText("年份：");

        yearBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017" }));

        jLabel8.setText("月份：");

        startMBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel9.setText("--");

        endMBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSno)
                            .addComponent(txtSgrade, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSname)
                            .addComponent(txtSdept, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSsex, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(txtDno)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnLoad)
                        .addGap(28, 28, 28)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startMBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endMBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(cobCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(cobCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(startMBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(endMBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtSsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnQuit))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //查找
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        switch(this.cobCondition.getSelectedIndex()){
            case 0:
                List <tManageStu> list0 = new ArrayList();
                list0.add(sbiz.findBySno(this.txtCondition.getText().trim()));
                showOnTable(list0);             
                break;
            case 1:
                List<tManageStu> list1 = sbiz.findBySname(this.txtCondition.getText().trim());
                showOnTable(list1);
                break;
            case 2:
                List<tManageStu> list2 = sbiz.findBySsex(this.txtCondition.getText().trim());
                showOnTable(list2);
                break;
            case 3:
                List<tManageStu> list3 = sbiz.findBySgrade(this.txtCondition.getText().trim());
                showOnTable(list3);
                break;
            case 4:
                List<tManageStu> list4 = sbiz.findBySdept(this.txtCondition.getText().trim());
                showOnTable(list4);
                break;
            case 5:
                List<tManageStu> list5 = sbiz.findByDno(this.txtCondition.getText().trim());
                showOnTable(list5);
            case 6:
                /*
                String startDate = this.yearBox.getSelectedItem().toString()+"-"+this.startMBox.getSelectedItem().toString()+"-"+"01";
                String endDate = this.yearBox.getSelectedItem().toString()+"-"+Integer.toString(this.endMBox.getSelectedIndex()+2)+"-"+"01";
                */
                String startDate = this.start.getText();
                String endDate = this.end.getText();
                List<tManageStu> list6 = sbiz.findByScin(startDate, endDate);
                showOnTable(list6);
                       
                break;
            case 7:
                List<tManageStu> list7 = sbiz.findByCondition(this.txtCondition.getText().trim());
                showOnTable(list7);
                break;
            default:
                JOptionPane.showMessageDialog(this, "错误！");
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    //载入
    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        List<tManageStu> list = sbiz.findAll();
        showOnTable(list);
    }//GEN-LAST:event_btnLoadActionPerformed
    //重置
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearIput();
        this.btnSave.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnCancelActionPerformed
    //增加
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String Sno = this.txtSno.getText().trim();
        String Sname = this.txtSname.getText().trim();
        String Ssex = this.txtSsex.getText().trim();
        String Sgrade = this.txtSgrade.getText().trim();
        String Sdept = this.txtSdept.getText().trim();
        String Dno = this.txtDno.getText().trim();
        if(StringUtil.checkLength(Sno)==false){
            JOptionPane.showMessageDialog(this, "学号不能为空！");
            return ;
        }
        else if(sbiz.findStudent(Sno)) {
            JOptionPane.showMessageDialog(this, "此学号已存在！");
            return;
        }
        else if(StringUtil.checkLength(Sname)==false) {
            JOptionPane.showMessageDialog(this, "姓名不能为空！");
            return ;
        }
        else if(StringUtil.checkLength(Ssex)==false) {
            JOptionPane.showMessageDialog(this, "性别不能为空！");
            return ;
        }
        else if(StringUtil.checkLength(Sgrade)==false) {
            JOptionPane.showMessageDialog(this, "年级不能为空！");
            return ;
        }
        else if(StringUtil.checkLength(Sdept)==false) {
            JOptionPane.showMessageDialog(this, "院系不能为空！");
            return ;
        }
        else if(StringUtil.checkLength(Dno)==false) {
            JOptionPane.showMessageDialog(this, "宿舍号不能为空！");
            return ;
        }
        tManageStu s = new tManageStu(Sno,Sname,Ssex,Integer.parseInt(Sgrade),Sdept,Dno);
        boolean result = sbiz.add(s);
        if(result == true) {
            JOptionPane.showMessageDialog(this, "添加成功");
            List<tManageStu> list = sbiz.findAll(); 
            showOnTable(list);
        }else{
            JOptionPane.showMessageDialog(this, "添加失败");
        }
        clearIput();
    }//GEN-LAST:event_btnAddActionPerformed
    //删除
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int answer = JOptionPane.showConfirmDialog(this, "您确定要删除吗？");
        if(answer == JOptionPane.YES_OPTION){
            String Sno = this.txtSno.getText();
            boolean result = sbiz.delete(Sno);
            if(result == true){
                JOptionPane.showMessageDialog(this, "删除成功");
                List<tManageStu> list = sbiz.findAll(); 
                showOnTable(list);
            }else{
                 JOptionPane.showMessageDialog(this, "删除失败");
            }
            clearIput();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    //表的鼠标事件
    private void tabStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabStudentMouseClicked
        int row = this.tabStudent.getSelectedRow();
        this.txtSno.setText(this.tabStudent.getValueAt(row,0)+"");
        shortname = this.tabStudent.getValueAt(row,0)+"";
        this.txtSname.setText(this.tabStudent.getValueAt(row,1)+"");
        this.txtSsex.setText(this.tabStudent.getValueAt(row,2)+"");
        this.txtSgrade.setText(this.tabStudent.getValueAt(row,3)+"");
        this.txtSdept.setText(this.tabStudent.getValueAt(row,4)+"");
        this.txtDno.setText(this.tabStudent.getValueAt(row,5)+"");
        this.btnSave.setEnabled(true);
        this.btnDelete.setEnabled(true);
    }//GEN-LAST:event_tabStudentMouseClicked
    //修改并保存
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String Sno = this.txtSno.getText().trim();
        String Sname = this.txtSname.getText().trim();
        String Ssex = this.txtSsex.getText().trim();
        String Sgrade = this.txtSgrade.getText().trim();
        String Sdept = this.txtSdept.getText().trim();
        String Dno = this.txtDno.getText().trim();
        if(StringUtil.checkLength(Sno)==false){
            JOptionPane.showMessageDialog(this, "学号不能为空！");
            return ;
        }
        else if(sbiz.findStudent(Sno)&& !Sno.equals(shortname)) {
            JOptionPane.showMessageDialog(this, "此学号已存在！");
            return;
        }
        else if(StringUtil.checkLength(Sname)==false) {
            JOptionPane.showMessageDialog(this, "姓名不能为空！");
            return ;
        }
        else if(StringUtil.checkLength(Ssex)==false) {
            JOptionPane.showMessageDialog(this, "性别不能为空！");
            return ;
        }
        else if(StringUtil.checkLength(Sgrade)==false) {
            JOptionPane.showMessageDialog(this, "年级不能为空！");
            return ;
        }
        else if(StringUtil.checkLength(Sdept)==false) {
            JOptionPane.showMessageDialog(this, "院系不能为空！");
            return ;
        }
        else if(StringUtil.checkLength(Dno)==false) {
            JOptionPane.showMessageDialog(this, "宿舍号不能为空！");
            return ;
        }
        tManageStu s = new tManageStu(Sno,Sname,Ssex,Integer.parseInt(Sgrade),Sdept,Dno);
        boolean result = sbiz.add(s);
        if(result == true) {
            JOptionPane.showMessageDialog(this, "添加成功");
            List<tManageStu> list = sbiz.findAll(); 
            showOnTable(list);
        }else{
            JOptionPane.showMessageDialog(this, "添加失败");
        }
        clearIput();
    }//GEN-LAST:event_btnSaveActionPerformed
    

            
    public void showOnTable(List<tManageStu> list){
        //1.获取指定表格（tblProduct）模型
        DefaultTableModel dtm = 
                (DefaultTableModel ) this.tabStudent.getModel();
        //2.清空表格信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        //3.显示数据
        for(tManageStu s:list){
            Vector vt = new Vector();
            vt.add(s.getSno());
            vt.add(s.getSname());
            vt.add(s.getSsex());
            vt.add(s.getSgrade());
            vt.add(s.getSdept());
            vt.add(s.getDno());
            dtm.addRow(vt);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cobCondition;
    private com.ouc.cpss.util.DateChooserJButton end;
    private javax.swing.JComboBox endMBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.ouc.cpss.util.DateChooserJButton start;
    private javax.swing.JComboBox startMBox;
    private javax.swing.JTable tabStudent;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtDno;
    private javax.swing.JTextField txtSdept;
    private javax.swing.JTextField txtSgrade;
    private javax.swing.JTextField txtSname;
    private javax.swing.JTextField txtSno;
    private javax.swing.JTextField txtSsex;
    private javax.swing.JComboBox yearBox;
    // End of variables declaration//GEN-END:variables



    private void clearIput() {
        this.txtSno.setText("");
        this.txtSname.setText("");
        this.txtSsex.setText("");
        this.txtSgrade.setText("");
        this.txtSdept.setText("");
        this.txtDno.setText("");
    }
}
