/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dm.view;

import dm.biz.LeaveSchoolBiz;
import dm.biz.LeaveSchoolBizImpl;
import dm.biz.StudentBiz;
import dm.biz.StudentBizImpl;
import dm.biz.tStuLeaveBiz;
import dm.biz.tStuLeaveBizImpl;
import dm.po.LeaveSchool;
import dm.po.Student;
import dm.util.FrameUtil;
import dm.util.LocationUtil;
import dm.vo.SD;
import dm.vo.SD;
import dm.vo.tStuLeave;
import dm.vo.tStuLeave;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 28104
 */
public class TstuLeaveFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form TstuLeaveFrame
     */
    tStuLeaveBiz lsbiz= new tStuLeaveBizImpl();
    StudentBiz sbiz = new StudentBizImpl();
    
    LeaveSchoolBiz LSdao= new LeaveSchoolBizImpl();
    public TstuLeaveFrame() {
        initComponents();
        this.setTitle("学生离/返校信息");
        LocationUtil.setScreenCenter(this); //窗口居中
        this.btnReturn.setEnabled(false);
        this.btnLeave.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LeaveTable = new javax.swing.JTable();
        cobCondition = new javax.swing.JComboBox();
        txtCondition = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSltime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSreturn = new javax.swing.JTextField();
        btnLoad = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnFindStu = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        LeaveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "学号", "姓名", "宿舍号", "离校时间", "返校时间"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LeaveTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeaveTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LeaveTable);

        cobCondition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "全部", "已返校", "未返校", "学号", "姓名", "宿舍号" }));

        txtCondition.setText("请输入条件");
        txtCondition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConditionMouseClicked(evt);
            }
        });

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("学号：");

        txtSno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSnoMouseClicked(evt);
            }
        });

        jLabel2.setText("姓名：");

        txtSname.setEditable(false);

        jLabel3.setText("宿舍号：");

        txtDno.setEditable(false);

        jLabel4.setText("离校时间：");

        txtSltime.setEditable(false);

        jLabel5.setText("返校时间：");

        txtSreturn.setEditable(false);

        btnLoad.setText("载入");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnLeave.setText("离校写入");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        btnReturn.setText("返校确认");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnFindStu.setText("信息查询");
        btnFindStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindStuActionPerformed(evt);
            }
        });

        btnQuit.setText("退出");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 427, Short.MAX_VALUE)
                .addComponent(cobCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSno, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSname, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDno, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSltime, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLoad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFindStu)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnLeave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReturn)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(28, 28, 28)
                                .addComponent(btnQuit))
                            .addComponent(txtSreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSltime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSreturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad)
                    .addComponent(btnLeave)
                    .addComponent(btnReturn)
                    .addComponent(btnFindStu)
                    .addComponent(btnQuit)
                    .addComponent(btnDelete))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        ClearInput1();
        List<tStuLeave> list=lsbiz.findAll();
        showOntable(list);
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        ClearInput1();
        String choose = this.cobCondition.getSelectedItem().toString();
        String condition = this.txtCondition.getText();
        if(choose.equals("全部"))
        {
            List<tStuLeave> list=lsbiz.findAll();
            showOntable(list);
        }else if(choose.equals("已返校"))
        {
            List<tStuLeave> list=lsbiz.isORNotReturn(true);
            showOntable(list);
        }
        else if(choose.equals("未返校"))
        {
            List<tStuLeave> list=lsbiz.isORNotReturn(false);
            showOntable(list);
        }else if(choose.equals("学号"))
        {
            List<tStuLeave> list=lsbiz.findBySno(condition);
            showOntable(list);
        }
        else if(choose.equals("姓名"))
        {
            List<tStuLeave> list=lsbiz.findBySname(condition);
            showOntable(list);
        }
        else
        {
            List<tStuLeave> list=lsbiz.findByDno(condition);
            showOntable(list);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void LeaveTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaveTableMouseClicked
        // TODO add your handling code here:
        //鼠标选中某行，信息显示到输入面板
        int Row=this.LeaveTable.getSelectedRow();
        this.txtSno.setText(this.LeaveTable.getValueAt(Row,0)+"");
        this.txtSname.setText(this.LeaveTable.getValueAt(Row,1)+"");
        this.txtDno.setText(this.LeaveTable.getValueAt(Row,2)+"");
        this.txtSltime.setText(this.LeaveTable.getValueAt(Row,3)+"");
        this.txtSreturn.setText(this.LeaveTable.getValueAt(Row,4)+"");
        String Sreturn=this.txtSreturn.getText().trim();
        if(Sreturn.equals("null"))
        {
            this.btnReturn.setEnabled(true);
        }
        else
        {
            this.btnReturn.setEnabled(false);
        }
        this.btnDelete.setEnabled(true);
        this.btnLeave.setEnabled(false);
    }//GEN-LAST:event_LeaveTableMouseClicked

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        // 退出前的清理工作
        FrameUtil.framemap.remove(TstuLeaveFrame.class.getName());
        this.dispose();  
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        // TODO add your handling code here:
        java.sql.Date currentDate = new java.sql.Date(System.currentTimeMillis());
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        formatter.format(currentDate);
        String Sno = this.txtSno.getText().trim();
        String Sname = this.txtSname.getText().trim();
        LeaveSchool ls= new LeaveSchool(Sno,currentDate,null);
        int answer = JOptionPane.showConfirmDialog(this, "学号："+Sno+"\n姓名："+Sname+"\n离校时间："+currentDate+"\n\n您确定要写入吗？");
        if(answer == JOptionPane.YES_OPTION)
        {   
            if(LSdao.add(ls))
            {
                JOptionPane.showMessageDialog(this,"写入成功！");
                //重新载入
                List<tStuLeave> list=lsbiz.findAll();
                showOntable(list);
                ClearInput1();
                this.btnLeave.setEnabled(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"写入失败！");
            }
        }else {
        }
        
    }//GEN-LAST:event_btnLeaveActionPerformed

    private void btnFindStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindStuActionPerformed
        // TODO add your handling code here:
        // 获取离校信息
        ClearInput();
        String Sno = this.txtSno.getText().trim();
        // 查询学生信息S
        Student s = sbiz.findBySno(Sno);
        this.txtSname.setText(s.getSname()+"");
        
        this.txtDno.setText(s.getDno()+"");
        this.btnLeave.setEnabled(true);
        this.btnReturn.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnFindStuActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String Sno = this.txtSno.getText().trim();
        String Sname =this.txtSname.getText().trim();
        String Sltime=this.txtSltime.getText().trim();
        String Sreturn=this.txtSreturn.getText().trim();
        java.sql.Date sqlSltime=null;
        java.sql.Date sqlSreturn=null;
        sqlSltime=java.sql.Date.valueOf(Sltime);
        int answer=0;
        if(!Sreturn.equals("null"))
        {
            sqlSreturn=java.sql.Date.valueOf(Sreturn);
            answer = JOptionPane.showConfirmDialog(this, "学号："+Sno+"\n姓名："+Sname+"\n离校时间："+sqlSltime+"\n返校时间："+sqlSreturn+"\n\n您确定要删除吗？");
        }
        else
        {
            Sreturn="还未返校";
            answer = JOptionPane.showConfirmDialog(this, "学号："+Sno+"\n姓名："+Sname+"\n离校时间："+sqlSltime+"\n返校时间："+Sreturn+"\n\n您确定要删除吗？");
        }
        if(answer == JOptionPane.YES_OPTION)
        {
           if(LSdao.delete(Sno, sqlSltime))
           {
               JOptionPane.showMessageDialog(this,"删除成功！");
               //重新载入
                List<tStuLeave> list=lsbiz.findAll();
                showOntable(list);
                ClearInput1();
                this.btnDelete.setEnabled(false);
           }
           else
          {
               JOptionPane.showMessageDialog(this,"删除失败！");
          }
        }else{
        }
            
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        java.sql.Date currentDate = new java.sql.Date(System.currentTimeMillis());
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        formatter.format(currentDate);
        String Sno = this.txtSno.getText().trim();
        String Sname =this.txtSname.getText().trim();
        String Sltime=this.txtSltime.getText().trim();
        java.sql.Date sqlSltime=null;
        sqlSltime=java.sql.Date.valueOf(Sltime);
        int answer=0;
        answer = JOptionPane.showConfirmDialog(this, "学号："+Sno+"\n姓名："+Sname+"\n离校时间："+sqlSltime+"\n返校时间："+currentDate+"\n\n您确定要确认吗？");
        if(answer ==JOptionPane.YES_OPTION){
        if(LSdao.update(Sno, sqlSltime, currentDate))
            {
            JOptionPane.showMessageDialog(this,"返校确认成功！");
               //重新载入
                List<tStuLeave> list=lsbiz.findAll();
                showOntable(list);
                ClearInput1();
                this.btnReturn.setEnabled(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"返校确认失败！");
            }
        }
        else{
        }
        
    }//GEN-LAST:event_btnReturnActionPerformed

    private void txtConditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConditionMouseClicked
        // TODO add your handling code here:
        this.txtCondition.setText("");
    }//GEN-LAST:event_txtConditionMouseClicked

    private void txtSnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSnoMouseClicked
        // TODO add your handling code here:
        ClearInput1();
    }//GEN-LAST:event_txtSnoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LeaveTable;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFindStu;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cobCondition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtDno;
    private javax.swing.JTextField txtSltime;
    private javax.swing.JTextField txtSname;
    private javax.swing.JTextField txtSno;
    private javax.swing.JTextField txtSreturn;
    // End of variables declaration//GEN-END:variables

    private void showOntable(List<tStuLeave> list) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        //获取表的模型
        DefaultTableModel dtm=(DefaultTableModel) this.LeaveTable.getModel();
        //清空表格信息
        while(dtm.getRowCount()>0)
        {
            dtm.removeRow(0);
        }
        //显示数据
        for(tStuLeave ls:list)
        {
            Vector vt=new Vector();
            vt.add(ls.getSno());
            vt.add(ls.getSname());
            vt.add(ls.getDno());
            vt.add(ls.getSltime());
            vt.add(ls.getSreturn());
            dtm.addRow(vt);
        }
    }
    private void ClearInput(){
        //this.txtSno.setText("");
        this.txtSname.setText("");
        this.txtDno.setText("");
        this.txtSltime.setText("");
        this.txtSreturn.setText("");
    }
    private void ClearInput1(){
        this.txtSno.setText("");
        this.txtSname.setText("");
        this.txtDno.setText("");
        this.txtSltime.setText("");
        this.txtSreturn.setText("");
    }
}
